version: '3'

services:
  latex:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ../:/workspaces/Raman:cached

    command: sleep infinity 

    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
